export interface Referral {
    id: string;
    name: string;
    referredBy: string;
    dateJoined: string;
    totalReferralCommission: string;
    amountReferred?: number; // For Top Referrals view
    totalCommissionEarned?: string; // For Top Referrals view
}

// Mock referral data - updated to 50 referrals
export const mockReferrals: Referral[] = [
    {
        id: "#12345678",
        name: "Chinedu Onwudiwe",
        referredBy: "Chinedu Onwudiwe",
        dateJoined: "May 13th, 2025",
        totalReferralCommission: "₦10,000",
        amountReferred: 100,
        totalCommissionEarned: "₦10,000",
    },
    {
        id: "#12345679",
        name: "Piriye Gbobo",
        referredBy: "Piriye Gbobo",
        dateJoined: "May 12th, 2025",
        totalReferralCommission: "₦5,000",
        amountReferred: 90,
        totalCommissionEarned: "₦5,000",
    },
    {
        id: "#12345680",
        name: "Amara Okoro",
        referredBy: "Chinedu Onwudiwe",
        dateJoined: "May 11th, 2025",
        totalReferralCommission: "₦15,200",
        amountReferred: 150,
        totalCommissionEarned: "₦15,200",
    },
    {
        id: "#12345681",
        name: "Tunde Ajayi",
        referredBy: "Piriye Gbobo",
        dateJoined: "May 11th, 2025",
        totalReferralCommission: "₦8,900",
        amountReferred: 80,
        totalCommissionEarned: "₦8,900",
    },
    {
        id: "#12345682",
        name: "Fatima Musa",
        referredBy: "Amara Okoro",
        dateJoined: "May 10th, 2025",
        totalReferralCommission: "₦22,000",
        amountReferred: 200,
        totalCommissionEarned: "₦22,000",
    },
    {
        id: "#12345683",
        name: "Emeka Nnadi",
        referredBy: "Tunde Ajayi",
        dateJoined: "May 10th, 2025",
        totalReferralCommission: "₦4,500",
        amountReferred: 40,
        totalCommissionEarned: "₦4,500",
    },
    {
        id: "#12345684",
        name: "Hauwa Ibrahim",
        referredBy: "Fatima Musa",
        dateJoined: "May 9th, 2025",
        totalReferralCommission: "₦30,150",
        amountReferred: 280,
        totalCommissionEarned: "₦30,150",
    },
    {
        id: "#12345685",
        name: "Obi Eze",
        referredBy: "Emeka Nnadi",
        dateJoined: "May 9th, 2025",
        totalReferralCommission: "₦1,200",
        amountReferred: 10,
        totalCommissionEarned: "₦1,200",
    },
    {
        id: "#12345686",
        name: "Nkechi Uche",
        referredBy: "Hauwa Ibrahim",
        dateJoined: "May 8th, 2025",
        totalReferralCommission: "₦11,500",
        amountReferred: 110,
        totalCommissionEarned: "₦11,500",
    },
    {
        id: "#12345687",
        name: "Kunle Adebayo",
        referredBy: "Obi Eze",
        dateJoined: "May 8th, 2025",
        totalReferralCommission: "₦6,750",
        amountReferred: 65,
        totalCommissionEarned: "₦6,750",
    },
    {
        id: "#12345688",
        name: "Aisha Bello",
        referredBy: "Nkechi Uche",
        dateJoined: "May 7th, 2025",
        totalReferralCommission: "₦18,000",
        amountReferred: 170,
        totalCommissionEarned: "₦18,000",
    },
    {
        id: "#12345689",
        name: "Ifeanyi Kalu",
        referredBy: "Kunle Adebayo",
        dateJoined: "May 7th, 2025",
        totalReferralCommission: "₦9,900",
        amountReferred: 95,
        totalCommissionEarned: "₦9,900",
    },
    {
        id: "#12345690",
        name: "Gloria Ekeh",
        referredBy: "Aisha Bello",
        dateJoined: "May 6th, 2025",
        totalReferralCommission: "₦3,500",
        amountReferred: 30,
        totalCommissionEarned: "₦3,500",
    },
    {
        id: "#12345691",
        name: "Sikiru Oladipo",
        referredBy: "Ifeanyi Kalu",
        dateJoined: "May 6th, 2025",
        totalReferralCommission: "₦14,000",
        amountReferred: 130,
        totalCommissionEarned: "₦14,000",
    },
    {
        id: "#12345692",
        name: "Jessica Ada",
        referredBy: "Gloria Ekeh",
        dateJoined: "May 5th, 2025",
        totalReferralCommission: "₦2,800",
        amountReferred: 25,
        totalCommissionEarned: "₦2,800",
    },
    {
        id: "#12345693",
        name: "Nonso Ibe",
        referredBy: "Sikiru Oladipo",
        dateJoined: "May 5th, 2025",
        totalReferralCommission: "₦28,000",
        amountReferred: 260,
        totalCommissionEarned: "₦28,000",
    },
    {
        id: "#12345694",
        name: "Zara Abubakar",
        referredBy: "Jessica Ada",
        dateJoined: "May 4th, 2025",
        totalReferralCommission: "₦7,600",
        amountReferred: 70,
        totalCommissionEarned: "₦7,600",
    },
    {
        id: "#12345695",
        name: "Dayo Bankole",
        referredBy: "Nonso Ibe",
        dateJoined: "May 4th, 2025",
        totalReferralCommission: "₦19,500",
        amountReferred: 180,
        totalCommissionEarned: "₦19,500",
    },
    {
        id: "#12345696",
        name: "Blessing Osagie",
        referredBy: "Zara Abubakar",
        dateJoined: "May 3rd, 2025",
        totalReferralCommission: "₦1,800",
        amountReferred: 15,
        totalCommissionEarned: "₦1,800",
    },
    {
        id: "#12345697",
        name: "Michael Okon",
        referredBy: "Dayo Bankole",
        dateJoined: "May 3rd, 2025",
        totalReferralCommission: "₦12,300",
        amountReferred: 115,
        totalCommissionEarned: "₦12,300",
    },
    {
        id: "#12345698",
        name: "Chinwe Eze",
        referredBy: "Blessing Osagie",
        dateJoined: "May 2nd, 2025",
        totalReferralCommission: "₦25,000",
        amountReferred: 240,
        totalCommissionEarned: "₦25,000",
    },
    {
        id: "#12345699",
        name: "Segun Obasanjo",
        referredBy: "Michael Okon",
        dateJoined: "May 2nd, 2025",
        totalReferralCommission: "₦900",
        amountReferred: 8,
        totalCommissionEarned: "₦900",
    },
    {
        id: "#12345700",
        name: "Adaobi Ibekwe",
        referredBy: "Chinwe Eze",
        dateJoined: "May 1st, 2025",
        totalReferralCommission: "₦16,000",
        amountReferred: 155,
        totalCommissionEarned: "₦16,000",
    },
    {
        id: "#12345701",
        name: "Femi Awolowo",
        referredBy: "Segun Obasanjo",
        dateJoined: "May 1st, 2025",
        totalReferralCommission: "₦5,500",
        amountReferred: 50,
        totalCommissionEarned: "₦5,500",
    },
    {
        id: "#12345702",
        name: "Amina Yusuf",
        referredBy: "Adaobi Ibekwe",
        dateJoined: "April 30th, 2025",
        totalReferralCommission: "₦21,000",
        amountReferred: 195,
        totalCommissionEarned: "₦21,000",
    },
    {
        id: "#12345703",
        name: "Jude Egbuna",
        referredBy: "Femi Awolowo",
        dateJoined: "April 30th, 2025",
        totalReferralCommission: "₦3,200",
        amountReferred: 28,
        totalCommissionEarned: "₦3,200",
    },
    {
        id: "#12345704",
        name: "Precious Davies",
        referredBy: "Amina Yusuf",
        dateJoined: "April 29th, 2025",
        totalReferralCommission: "₦13,400",
        amountReferred: 125,
        totalCommissionEarned: "₦13,400",
    },
    {
        id: "#12345705",
        name: "Yemi Alade",
        referredBy: "Jude Egbuna",
        dateJoined: "April 29th, 2025",
        totalReferralCommission: "₦7,100",
        amountReferred: 68,
        totalCommissionEarned: "₦7,100",
    },
    {
        id: "#12345706",
        name: "Chidera Ojukwu",
        referredBy: "Precious Davies",
        dateJoined: "April 28th, 2025",
        totalReferralCommission: "₦24,000",
        amountReferred: 225,
        totalCommissionEarned: "₦24,000",
    },
    {
        id: "#12345707",
        name: "David Chukwu",
        referredBy: "Yemi Alade",
        dateJoined: "April 28th, 2025",
        totalReferralCommission: "₦4,900",
        amountReferred: 45,
        totalCommissionEarned: "₦4,900",
    },
    {
        id: "#12345708",
        name: "Funke Ade",
        referredBy: "Chidera Ojukwu",
        dateJoined: "April 27th, 2025",
        totalReferralCommission: "₦17,500",
        amountReferred: 165,
        totalCommissionEarned: "₦17,500",
    },
    {
        id: "#12345709",
        name: "Kelvin Etim",
        referredBy: "David Chukwu",
        dateJoined: "April 27th, 2025",
        totalReferralCommission: "₦1,500",
        amountReferred: 12,
        totalCommissionEarned: "₦1,500",
    },
    {
        id: "#12345710",
        name: "Chioma Nwosu",
        referredBy: "Funke Ade",
        dateJoined: "April 26th, 2025",
        totalReferralCommission: "₦10,800",
        amountReferred: 102,
        totalCommissionEarned: "₦10,800",
    },
    {
        id: "#12345711",
        name: "Gabriel Okeke",
        referredBy: "Kelvin Etim",
        dateJoined: "April 26th, 2025",
        totalReferralCommission: "₦6,200",
        amountReferred: 58,
        totalCommissionEarned: "₦6,200",
    },
    {
        id: "#12345712",
        name: "Kemi Olaniyan",
        referredBy: "Chioma Nwosu",
        dateJoined: "April 25th, 2025",
        totalReferralCommission: "₦20,500",
        amountReferred: 190,
        totalCommissionEarned: "₦20,500",
    },
    {
        id: "#12345713",
        name: "Obinna Egbunike",
        referredBy: "Gabriel Okeke",
        dateJoined: "April 25th, 2025",
        totalReferralCommission: "₦2,500",
        amountReferred: 22,
        totalCommissionEarned: "₦2,500",
    },
    {
        id: "#12345714",
        name: "Ejiro Ovie",
        referredBy: "Kemi Olaniyan",
        dateJoined: "April 24th, 2025",
        totalReferralCommission: "₦11,900",
        amountReferred: 112,
        totalCommissionEarned: "₦11,900",
    },
    {
        id: "#12345715",
        name: "Jide Kosoko",
        referredBy: "Obinna Egbunike",
        dateJoined: "April 24th, 2025",
        totalReferralCommission: "₦8,000",
        amountReferred: 75,
        totalCommissionEarned: "₦8,000",
    },
    {
        id: "#12345716",
        name: "Zara Mohammed",
        referredBy: "Ejiro Ovie",
        dateJoined: "April 23rd, 2025",
        totalReferralCommission: "₦35,000",
        amountReferred: 320,
        totalCommissionEarned: "₦35,000",
    },
    {
        id: "#12345717",
        name: "Tony Odogwu",
        referredBy: "Jide Kosoko",
        dateJoined: "April 23rd, 2025",
        totalReferralCommission: "₦1,100",
        amountReferred: 9,
        totalCommissionEarned: "₦1,100",
    },
    {
        id: "#12345718",
        name: "Ugochi Ibe",
        referredBy: "Zara Mohammed",
        dateJoined: "April 22nd, 2025",
        totalReferralCommission: "₦15,700",
        amountReferred: 145,
        totalCommissionEarned: "₦15,700",
    },
    {
        id: "#12345719",
        name: "Lekan Popoola",
        referredBy: "Tony Odogwu",
        dateJoined: "April 22nd, 2025",
        totalReferralCommission: "₦9,300",
        amountReferred: 88,
        totalCommissionEarned: "₦9,300",
    },
    {
        id: "#12345720",
        name: "Pamela Peters",
        referredBy: "Ugochi Ibe",
        dateJoined: "April 21st, 2025",
        totalReferralCommission: "₦23,000",
        amountReferred: 215,
        totalCommissionEarned: "₦23,000",
    },
    {
        id: "#12345721",
        name: "Wale Ayodele",
        referredBy: "Lekan Popoola",
        dateJoined: "April 21st, 2025",
        totalReferralCommission: "₦4,200",
        amountReferred: 38,
        totalCommissionEarned: "₦4,200",
    },
    {
        id: "#12345722",
        name: "Ifunanya Eke",
        referredBy: "Pamela Peters",
        dateJoined: "April 20th, 2025",
        totalReferralCommission: "₦14,800",
        amountReferred: 138,
        totalCommissionEarned: "₦14,800",
    },
    {
        id: "#12345723",
        name: "Godwin Nwafor",
        referredBy: "Wale Ayodele",
        dateJoined: "April 20th, 2025",
        totalReferralCommission: "₦7,700",
        amountReferred: 72,
        totalCommissionEarned: "₦7,700",
    },
    {
        id: "#12345724",
        name: "Tope Akin",
        referredBy: "Ifunanya Eke",
        dateJoined: "April 19th, 2025",
        totalReferralCommission: "₦18,200",
        amountReferred: 172,
        totalCommissionEarned: "₦18,200",
    },
    {
        id: "#12345725",
        name: "Chiamaka Obi",
        referredBy: "Godwin Nwafor",
        dateJoined: "April 19th, 2025",
        totalReferralCommission: "₦3,800",
        amountReferred: 34,
        totalCommissionEarned: "₦3,800",
    },
    {
        id: "#12345726",
        name: "Bashir Aliyu",
        referredBy: "Tope Akin",
        dateJoined: "April 18th, 2025",
        totalReferralCommission: "₦26,000",
        amountReferred: 245,
        totalCommissionEarned: "₦26,000",
    },
    {
        id: "#12345727",
        name: "Zina Okoye",
        referredBy: "Chiamaka Obi",
        dateJoined: "April 18th, 2025",
        totalReferralCommission: "₦5,600",
        amountReferred: 52,
        totalCommissionEarned: "₦5,600",
    },
];

// Referral code and link
export const referralCode = "EHJYER1234";
export const referralLink = "htt://referral/code.com";
export const totalReferrals = 50;
