import Image1 from "/src/assets/Properties img/Image 1.jpg";
import Image2 from "/src/assets/Properties img/Image 2.jpg";
import Image3 from "/src/assets/Properties img/Image 3.jpg";
import Image4 from "/src/assets/Properties img/Image 4.jpg";
import Image5 from "/src/assets/Properties img/Image 5.jpg";
import Image6 from "/src/assets/Properties img/Image 6.jpg";
import Image7 from "/src/assets/Properties img/Image 7.jpg";
import Image8 from "/src/assets/Properties img/Image 8.jpg";
import Image9 from "/src/assets/Properties img/Image 9.jpg";
import Image10 from "/src/assets/Properties img/Image 10.jpg";
import Image11 from "/src/assets/Properties img/Image 11.jpg";
import Image12 from "/src/assets/Properties img/Image 12.jpg";

export interface Property {
  id: string;
  title: string;
  location: string;
  price: string;
  commission: string;
  image: string;
  images: string[]; // Array of multiple images
  type: string;
}

// All available images
const allImages = [
  Image1,
  Image2,
  Image3,
  Image4,
  Image5,
  Image6,
  Image7,
  Image8,
  Image9,
  Image10,
  Image11,
  Image12,
];

// Helper function to get a random main image
const getRandomImage = () => {
  const randomIndex = Math.floor(Math.random() * allImages.length);
  return allImages[randomIndex];
};

// Helper function to get a random subset of 6 images
const getRandomImageSet = () => {
  const shuffled = [...allImages].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 6);
};

// Data arrays for randomization
const locations = [
  "Lekki Phase 1, Lagos",
  "Ikeja GRA, Lagos",
  "Jabi, Abuja",
  "Trans Amadi, Port Harcourt",
  "Asokoro, Abuja",
  "Victoria Island, Lagos",
];
const prices = [
  "₦150,000,000",
  "₦85,000,000",
  "₦250,000,000",
  "₦45,000,000",
  "₦300,000,000",
];
const types = ["lands", "houses", "apartments", "commercial"];
const titles = [
  "Luxury Villa for Rent",
  "Prime Commercial Land",
  "Modern 3-Bedroom Flat",
  "Exclusive Penthouse Unit",
  "Spacious Duplex for Sale",
];

export const properties: Property[] = [
  // --- Your existing 16 mock properties ---
  {
    id: "prop-1",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image6, Image7],
    type: "lands",
  },
  {
    id: "prop-2",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image2,
    images: [Image2, Image3, Image4, Image5, Image6, Image7],
    type: "lands",
  },
  {
    id: "prop-3",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image3,
    images: [Image3, Image4, Image5, Image1, Image8, Image9],
    type: "lands",
  },
  {
    id: "prop-4",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image4,
    images: [Image4, Image5, Image1, Image2, Image10, Image11],
    type: "lands",
  },
  {
    id: "prop-5",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image5,
    images: [Image5, Image1, Image2, Image3, Image12, Image6],
    type: "lands",
  },
  {
    id: "prop-6",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image5, Image6],
    type: "lands",
  },
  {
    id: "prop-7",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image7, Image8],
    type: "lands",
  },
  {
    id: "prop-8",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image7, Image8],
    type: "lands",
  },
  {
    id: "prop-9",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image9, Image10],
    type: "lands",
  },
  {
    id: "prop-10",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image11, Image12],
    type: "lands",
  },
  {
    id: "prop-11",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image6, Image7],
    type: "lands",
  },
  {
    id: "prop-12",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image8, Image9],
    type: "lands",
  },
  {
    id: "prop-13",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image8, Image9],
    type: "lands",
  },
  {
    id: "prop-14",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image8, Image9],
    type: "lands",
  },
  {
    id: "prop-15",
    title: "Story Building for sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image8, Image9],
    type: "lands",
  },
  {
    id: "prop-16",
    title: "Land for Sale",
    location: "City of David, Lagos",
    price: "₦100,000,000",
    commission: "10% commission",
    image: Image1,
    images: [Image1, Image2, Image3, Image4, Image8, Image9],
    type: "lands",
  },
  // --- Start of 34 auto-generated properties to reach a total of 50 ---
  {
    id: "prop-17",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-18",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-19",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-20",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-21",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "12% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-22",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-23",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-24",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-25",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-26",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-27",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-28",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-29",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "12% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-30",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-31",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-32",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-33",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-34",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-35",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-36",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "12% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-37",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-38",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-39",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-40",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-41",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "12% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-42",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-43",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-44",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-45",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "12% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-46",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-47",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-48",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-49",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "10% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  {
    id: "prop-50",
    title: titles[Math.floor(Math.random() * titles.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    price: prices[Math.floor(Math.random() * prices.length)],
    commission: "7.5% commission",
    image: getRandomImage(),
    images: getRandomImageSet(),
    type: types[Math.floor(Math.random() * types.length)],
  },
  // --- End of 50 total properties ---
];
