// src/components/Dashboard components/filterData.ts

export interface Receipt {
  id: string;
  propertyName: string;
  clientName: string;
  amount: string;
  date: string;
  status: "Approved" | "Pending" | "Rejected" | "Under review";
  realtorId?: string; // Optional field to link receipt to a realtor
  realtorName?: string; // Optional field for realtor name
}

// Data for generating the remaining 86 receipts
const propertyNames = ["Lekki Gardens", "Victoria Island Towers", "Ajah Royal Estate", "Yaba Mega City", "Ikeja Business Park", "Eko Atlantic Residence"];
const clientNames = ["Tunde Alabi", "Ngozi Eze", "Aisha Bello", "Femi Adebayo", "Chika Okoro", "Hassan Musa", "Precious Eke", "Segun Kolawole", "Zara Ibrahim", "Ifeanyi Ude"];
const dates = ["May 14th, 2025", "May 15th, 2025", "May 16th, 2025", "May 17th, 2025", "May 18th, 2025"];
const statuses: Receipt["status"][] = ["Approved", "Pending", "Rejected", "Under review"];
const amounts = ["₦25,000", "₦50,000", "₦100,000", "₦150,000", "₦200,000"];

// Your existing 14 mock receipts
export const mockReceipts: Receipt[] = [
  {
    id: "#12345",
    propertyName: "Parkview Estate",
    clientName: "Iretiola Okunade",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Approved",
  },
  {
    id: "#12346",
    propertyName: "City of David Estate",
    clientName: "Izuokumo Aganaba",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Pending",
  },
  {
    id: "#12347",
    propertyName: "Oluwole Estate",
    clientName: "Seyi Olabode",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Approved",
  },
  {
    id: "#12348",
    propertyName: "Lagos Estate",
    clientName: "Kuroebi Timipre",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Rejected",
  },
  {
    id: "#12349",
    propertyName: "Iyana Iba Estate",
    clientName: "Tonbara Ziworitin",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Under review",
  },
  {
    id: "#12350",
    propertyName: "Police Post Estate",
    clientName: "Ekine Idamiebi",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Rejected",
  },
  {
    id: "#12351",
    propertyName: "Another Estate",
    clientName: "Seyi Weridide",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Pending",
  },
  {
    id: "#12352",
    propertyName: "Parkview Estate",
    clientName: "Simisola Okunade",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Approved",
  },
  {
    id: "#12353",
    propertyName: "City of David Estate",
    clientName: "Binabeyi Oyintare",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Pending",
  },
  {
    id: "#12354",
    propertyName: "Oluwole Estate",
    clientName: "Safiya Usman",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Approved",
  },
  {
    id: "#12355",
    propertyName: "Lagos Estate",
    clientName: "Chinyere Nwankwo",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Rejected",
  },
  {
    id: "#12356",
    propertyName: "Iyana Iba Estate",
    clientName: "Rahma Ahmad",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Under review",
  },
  {
    id: "#12357",
    propertyName: "Police Post Estate",
    clientName: "Ekine Idamiebi",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Rejected",
  },
  {
    id: "#12358",
    propertyName: "Another Estate",
    clientName: "Seyi Weridide",
    amount: "₦10,000",
    date: "May 13th, 2025",
    status: "Pending",
  },
  // --- Start of 86 auto-generated receipts to reach a total of 100 ---
  { id: "#12359", propertyName: propertyNames[0], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[0] },
  { id: "#12360", propertyName: propertyNames[1], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[1] },
  { id: "#12361", propertyName: propertyNames[2], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[2] },
  { id: "#12362", propertyName: propertyNames[3], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[3] },
  { id: "#12363", propertyName: propertyNames[4], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[0] },
  { id: "#12364", propertyName: propertyNames[5], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[1] },
  { id: "#12365", propertyName: propertyNames[0], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[2] },
  { id: "#12366", propertyName: propertyNames[1], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[3] },
  { id: "#12367", propertyName: propertyNames[2], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[0] },
  { id: "#12368", propertyName: propertyNames[3], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[1] },
  { id: "#12369", propertyName: propertyNames[4], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[2] },
  { id: "#12370", propertyName: propertyNames[5], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[3] },
  { id: "#12371", propertyName: propertyNames[0], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[0] },
  { id: "#12372", propertyName: propertyNames[1], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[1] },
  { id: "#12373", propertyName: propertyNames[2], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[2] },
  { id: "#12374", propertyName: propertyNames[3], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[3] },
  { id: "#12375", propertyName: propertyNames[4], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[0] },
  { id: "#12376", propertyName: propertyNames[5], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[1] },
  { id: "#12377", propertyName: propertyNames[0], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[2] },
  { id: "#12378", propertyName: propertyNames[1], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[3] },
  { id: "#12379", propertyName: propertyNames[2], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[0] },
  { id: "#12380", propertyName: propertyNames[3], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[1] },
  { id: "#12381", propertyName: propertyNames[4], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[2] },
  { id: "#12382", propertyName: propertyNames[5], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[3] },
  { id: "#12383", propertyName: propertyNames[0], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[0] },
  { id: "#12384", propertyName: propertyNames[1], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[1] },
  { id: "#12385", propertyName: propertyNames[2], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[2] },
  { id: "#12386", propertyName: propertyNames[3], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[3] },
  { id: "#12387", propertyName: propertyNames[4], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[0] },
  { id: "#12388", propertyName: propertyNames[5], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[1] },
  { id: "#12389", propertyName: propertyNames[0], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[2] },
  { id: "#12390", propertyName: propertyNames[1], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[3] },
  { id: "#12391", propertyName: propertyNames[2], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[0] },
  { id: "#12392", propertyName: propertyNames[3], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[1] },
  { id: "#12393", propertyName: propertyNames[4], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[2] },
  { id: "#12394", propertyName: propertyNames[5], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[3] },
  { id: "#12395", propertyName: propertyNames[0], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[0] },
  { id: "#12396", propertyName: propertyNames[1], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[1] },
  { id: "#12397", propertyName: propertyNames[2], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[2] },
  { id: "#12398", propertyName: propertyNames[3], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[3] },
  { id: "#12399", propertyName: propertyNames[4], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[0] },
  { id: "#12400", propertyName: propertyNames[5], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[1] },
  { id: "#12401", propertyName: propertyNames[0], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[2] },
  { id: "#12402", propertyName: propertyNames[1], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[3] },
  { id: "#12403", propertyName: propertyNames[2], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[0] },
  { id: "#12404", propertyName: propertyNames[3], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[1] },
  { id: "#12405", propertyName: propertyNames[4], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[2] },
  { id: "#12406", propertyName: propertyNames[5], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[3] },
  { id: "#12407", propertyName: propertyNames[0], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[0] },
  { id: "#12408", propertyName: propertyNames[1], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[1] },
  { id: "#12409", propertyName: propertyNames[2], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[2] },
  { id: "#12410", propertyName: propertyNames[3], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[3] },
  { id: "#12411", propertyName: propertyNames[4], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[0] },
  { id: "#12412", propertyName: propertyNames[5], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[1] },
  { id: "#12413", propertyName: propertyNames[0], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[2] },
  { id: "#12414", propertyName: propertyNames[1], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[3] },
  { id: "#12415", propertyName: propertyNames[2], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[0] },
  { id: "#12416", propertyName: propertyNames[3], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[1] },
  { id: "#12417", propertyName: propertyNames[4], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[2] },
  { id: "#12418", propertyName: propertyNames[5], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[3] },
  { id: "#12419", propertyName: propertyNames[0], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[0] },
  { id: "#12420", propertyName: propertyNames[1], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[1] },
  { id: "#12421", propertyName: propertyNames[2], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[2] },
  { id: "#12422", propertyName: propertyNames[3], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[3] },
  { id: "#12423", propertyName: propertyNames[4], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[0] },
  { id: "#12424", propertyName: propertyNames[5], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[1] },
  { id: "#12425", propertyName: propertyNames[0], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[2] },
  { id: "#12426", propertyName: propertyNames[1], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[3] },
  { id: "#12427", propertyName: propertyNames[2], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[0] },
  { id: "#12428", propertyName: propertyNames[3], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[1] },
  { id: "#12429", propertyName: propertyNames[4], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[2] },
  { id: "#12430", propertyName: propertyNames[5], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[3] },
  { id: "#12431", propertyName: propertyNames[0], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[0] },
  { id: "#12432", propertyName: propertyNames[1], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[1] },
  { id: "#12433", propertyName: propertyNames[2], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[2] },
  { id: "#12434", propertyName: propertyNames[3], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[3] },
  { id: "#12435", propertyName: propertyNames[4], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[0] },
  { id: "#12436", propertyName: propertyNames[5], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[1] },
  { id: "#12437", propertyName: propertyNames[0], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[2] },
  { id: "#12438", propertyName: propertyNames[1], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[3] },
  { id: "#12439", propertyName: propertyNames[2], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[0] },
  { id: "#12440", propertyName: propertyNames[3], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[1] },
  { id: "#12441", propertyName: propertyNames[4], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[2] },
  { id: "#12442", propertyName: propertyNames[5], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[3] },
  { id: "#12443", propertyName: propertyNames[0], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[0] },
  { id: "#12444", propertyName: propertyNames[1], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[1] },
  { id: "#12445", propertyName: propertyNames[2], clientName: clientNames[6], amount: amounts[3], date: dates[1], status: statuses[2] },
  { id: "#12446", propertyName: propertyNames[3], clientName: clientNames[7], amount: amounts[4], date: dates[2], status: statuses[3] },
  { id: "#12447", propertyName: propertyNames[4], clientName: clientNames[8], amount: amounts[0], date: dates[3], status: statuses[0] },
  { id: "#12448", propertyName: propertyNames[5], clientName: clientNames[9], amount: amounts[1], date: dates[4], status: statuses[1] },
  { id: "#12449", propertyName: propertyNames[0], clientName: clientNames[0], amount: amounts[2], date: dates[0], status: statuses[2] },
  { id: "#12450", propertyName: propertyNames[1], clientName: clientNames[1], amount: amounts[3], date: dates[1], status: statuses[3] },
  { id: "#12451", propertyName: propertyNames[2], clientName: clientNames[2], amount: amounts[4], date: dates[2], status: statuses[0] },
  { id: "#12452", propertyName: propertyNames[3], clientName: clientNames[3], amount: amounts[0], date: dates[3], status: statuses[1] },
  { id: "#12453", propertyName: propertyNames[4], clientName: clientNames[4], amount: amounts[1], date: dates[4], status: statuses[2] },
  { id: "#12454", propertyName: propertyNames[5], clientName: clientNames[5], amount: amounts[2], date: dates[0], status: statuses[3] },
  // --- End of 100 total receipts ---
];